[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"

[[context.branch-deploy]]
  context = "deploy-preview"
  command = "npm run build-preview"
  publish = "dist"